### ISSUE TITLE
execution error

### ISSUE THREAD

**Issue by martin-raden** [Alexander-Mitrofanov/CRISPRspacerEvolution#8]
Hi Alex,

I get (with the identify call) the following error on the server:

```sh
Traceback (most recent call last):
  File "/data/birna01/Software/CRISPRspacerEvolution/1.0.0/CRISPRidentify/CRISPRidentify.py", line 310, in <module>
    main()
  File "/data/birna01/Software/CRISPRspacerEvolution/1.0.0/CRISPRidentify/CRISPRidentify.py", line 295, in main
    run_over_one_file(complete_path_file, folder_result, pickle_folder, json_folder)
  File "/data/birna01/Software/CRISPRspacerEvolution/1.0.0/CRISPRidentify/CRISPRidentify.py", line 273, in run_over_one_file
    absolute_directory_path=script_absolute_path)
  File "/data/birna01/Software/CRISPRidentify/github-master/components/pipeline.py", line 34, in __init__
    self._run_non_crispr_computation()
  File "/data/birna01/Software/CRISPRidentify/github-master/components/pipeline.py", line 79, in _run_non_crispr_computation
    absolute_directory_path=self.absolute_directory_path)
  File "/data/birna01/Software/CRISPRidentify/github-master/components/module_non_array_computations.py", line 37, in __init__
    self._calculate_all_non_array_values()
  File "/data/birna01/Software/CRISPRidentify/github-master/components/module_non_array_computations.py", line 49, in _calculate_all_non_array_values
    self._calculate_strand()
  File "/data/birna01/Software/CRISPRidentify/github-master/components/module_non_array_computations.py", line 172, in _calculate_strand
    absolute_directory_path=self.absolute_directory_path)
  File "/data/birna01/Software/CRISPRidentify/github-master/components/components_non_array_computations.py", line 115, in __init__
    self._compute_all_strands()
  File "/data/birna01/Software/CRISPRidentify/github-master/components/components_non_array_computations.py", line 141, in _compute_all_strands
    with open("ResultsStrand/CRISPRstrand_Summary.tsv", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'ResultsStrand/CRISPRstrand_Summary.tsv
```

the `Identify_Temp2494025` subfolder only contains
- `ResultsStrand` folder (empty)
- `CRISPR_arrays_for_strand.fa`  file with the following content..

```txt
>CRISPR_1_consensus
GTTTCAATCCACGCCCCCCGTCACCGAGGGGCGATGC
>CRISPR_2_consensus
GTTTCAATCCACGCCCCCCGTCACCGAGGGGCGATGC
>CRISPR_3_consensus
GTTTCAATCCACGCCCCCCGTCACCGAGGGGCGATGC
```

any ideas?

**Comment by martin-raden** [comment]
Furthermore: eventually, **all consensi in the result file are the same**... is this expected and wanted?

**Comment by Alexander-Mitrofanov** [comment]
Hey Martin i can not reproduce this error on my pc even if i run it from a different folder

**Comment by Alexander-Mitrofanov** [comment]
is there a chance that you use an old/release version of CRISPRidentify?
I will try to run everythig on a different pc tomorrow to see if i can reproduce this bug

**Comment by Alexander-Mitrofanov** [comment]
i remember even having a problem there with the paths and so on
that is why i have 
a, b = process.communicate()
#print(a, b)


if you can do print(a, b)
and print(cmd) i will figure the problem really quick i bet it is just the path

**Comment by martin-raden** [comment]
ok... now I am getting tensorflow errors related to pthread...

Currently testing without parallelization (cpu=1 parallel=F)

**Comment by martin-raden** [comment]
the pip-tensorflow ignores `OMP_NUM_THREAD` it seems ([link](https://stackoverflow.com/questions/58223422/how-to-use-openmp-parallelism-effectively-with-tensorflow-1-14-0))

trying to bypas via `TF` env vars ..([link](https://stackoverflow.com/questions/38187808/how-can-i-run-tensorflow-on-one-single-core))
